name: Test

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'website/*'
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'website/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Run linters
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Generate
      run: make generate

    - name: Confirm no diff
      run: |
        git diff --compact-summary --exit-code || \
          (echo "*** Unexpected differences after code generation. Run 'make generate' and commit."; exit 1)

    - name: Build
      run: make build

  test:
    name: 'Acc. Tests (OS: ${{ matrix.os }} / TF: ${{ matrix.terraform }})'
    needs: build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        terraform:
          - '0.12.*'
          - '1.5.*'
        mimir-version:
          - '2.11.0'
          - '2.12.0'
          - '2.13.0'
    steps:

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
        check-latest: true

    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Terraform ${{ matrix.terraform }}
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ matrix.terraform }}
        terraform_wrapper: false

    - name: Setup Grafana Mimir from ${{ matrix.mimir-version }}
      run: |
        docker pull grafana/mimir:${{ matrix.mimir-version }}
        docker run \
          -d \
          -p 8080:8080 \
          --name mimir \
          grafana/mimir:${{ matrix.mimir-version }} \
          -target=alertmanager,ruler \
          -tenant-federation.enabled=true \
          -ruler.tenant-federation.enabled=true

    - name: Run acceptance test
      run: MIMIR_VERSION=${{ matrix.mimir-version }} make testacc
